name: ltuc
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  
    sdk: flutter

  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.0.0
  
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0

  get_storage: ^2.1.1
  get: ^4.7.2 # state management
  geolocator: ^14.0.2 # for locations use
  googleapis_auth: ^2.0.0

  http: ^1.4.0

  intl: ^0.20.2

  permission_handler: ^12.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/png/
    - assets/jpg/
    - assets/svg/
    - assets/json/
    

  fonts:
    - family: Poppins-Reg
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Med
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: Tajawal-Reg
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: Tajawal-Med
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
    - family: Tajawal-Bold
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf

